export const AUTHENTICATE_USER = "AUTHENTICATION/ACTION/AUTHENTICATE_USER";
export const USER_AUTHENTICATED = "AUTHENTICATION/ACTION/USER_AUTHENTICATED";
export const AUTHENTICATE_USER_FAILED =
  "AUTHENTICATION/ACTION/AUTHENTICATE_USER_FAILED";
export const AUTHENTICATE_USER_SUCCESS =
  "AUTHENTICATION/ACTION/AUTHENTICATE_USER_SUCCESS";
export const AUTHENTICATE_USER_START =
  "AUTHENTICATION/ACTION/AUTHENTICATE_USER_START";
export const AUTHENTICATE_VERIFY = "AUTHENTICATION/ACTION/AUTHENTICATE_VERIFY";
export const USER_TOKEN_VALIDATED =
  "AUTHENTICATION/ACTION/USER_TOKEN_VALIDATED";
export const REGISTER_USER = "AUTHENTICATION/ACTION/REGISTER_USER";
export const ADD_USER_ADDRESS = "AUTHENTICATION/ACTION/ADD_USER_ADDRESS";

export const GET_USER_DATA = "AUTHENTICATION/ACTION/GET_USER_DATA";

export const GET_USER_HISTORY_DATA =
  "AUTHENTICATION/ACTION/GET_USER_HISTORY_DATA";
export const SET_USER_HISTORY_DATA =
  "AUTHENTICATION/ACTION/SET_USER_HISTORY_DATA";
